# Generated by Django 5.2.6 on 2025-09-19 02:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("schema_name", models.CharField(max_length=63, unique=True)),
                ("asterisk_host", models.CharField(max_length=255)),
                ("asterisk_ami_port", models.IntegerField(default=5038)),
                ("asterisk_ari_port", models.IntegerField(default=8088)),
                ("asterisk_ami_username", models.CharField(max_length=50)),
                ("asterisk_ami_secret", models.CharField(max_length=255)),
                ("asterisk_ari_username", models.CharField(max_length=50)),
                ("asterisk_ari_password", models.CharField(max_length=255)),
                ("rtp_port_range_start", models.IntegerField(default=10000)),
                ("rtp_port_range_end", models.IntegerField(default=20000)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CallSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asterisk_channel_id", models.CharField(max_length=255, unique=True)),
                ("asterisk_unique_id", models.CharField(max_length=255, unique=True)),
                (
                    "caller_id_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "caller_id_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dialed_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Call Detected"),
                            ("answered", "Call Answered"),
                            ("bridged", "Call Bridged"),
                            ("recording", "Recording Active"),
                            ("ended", "Call Ended"),
                            ("failed", "Call Failed"),
                        ],
                        default="detected",
                        max_length=20,
                    ),
                ),
                ("bridge_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "external_media_channel_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rtp_endpoint_host",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rtp_endpoint_port", models.IntegerField(blank=True, null=True)),
                ("session_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "call_start_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("call_answer_time", models.DateTimeField(blank=True, null=True)),
                ("call_end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_sessions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "call_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AudioRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "audio_format",
                    models.CharField(
                        choices=[
                            ("wav", "WAV"),
                            ("mp3", "MP3"),
                            ("ulaw", "μ-law"),
                            ("alaw", "A-law"),
                        ],
                        default="wav",
                        max_length=10,
                    ),
                ),
                ("sample_rate", models.IntegerField(default=8000)),
                ("channels", models.IntegerField(default=1)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("starting", "Recording Starting"),
                            ("active", "Recording Active"),
                            ("stopped", "Recording Stopped"),
                            ("processed", "Recording Processed"),
                            ("failed", "Recording Failed"),
                        ],
                        default="starting",
                        max_length=20,
                    ),
                ),
                ("recording_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "recording_start_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("recording_end_time", models.DateTimeField(blank=True, null=True)),
                ("transcription_text", models.TextField(blank=True, null=True)),
                ("transcription_confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_recordings",
                        to="core.callsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_recordings",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audio_recordings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrator"),
                            ("tenant_admin", "Tenant Administrator"),
                            ("operator", "Call Operator"),
                            ("viewer", "Call Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                (
                    "phone_extension",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("can_monitor_calls", models.BooleanField(default=False)),
                ("can_record_calls", models.BooleanField(default=False)),
                ("can_access_recordings", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=False)),
                ("permissions_metadata", models.JSONField(blank=True, default=dict)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "Global"), ("tenant", "Tenant-Specific")],
                        default="global",
                        max_length=10,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "system_configurations",
                "ordering": ["scope", "key"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "scope"],
                        name="system_conf_tenant__0e9616_idx",
                    ),
                    models.Index(fields=["key"], name="system_conf_key_35f9ec_idx"),
                ],
                "unique_together": {("scope", "key"), ("tenant", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(
                fields=["tenant", "status"], name="call_sessio_tenant__ec8b60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(
                fields=["asterisk_channel_id"], name="call_sessio_asteris_0bdca6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(
                fields=["asterisk_unique_id"], name="call_sessio_asteris_6c6e62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiorecording",
            index=models.Index(
                fields=["tenant", "status"], name="audio_recor_tenant__3cea60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiorecording",
            index=models.Index(
                fields=["call_session"], name="audio_recor_call_se_57f32c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["tenant", "role"], name="user_profil_tenant__9423f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="user_profil_user_id_fbe33d_idx"),
        ),
    ]
